export const pricingOptions = [
	{
		id: 1,
		title: "12 Months Subscription",
		totalPrice: 99,
		monthlyPrice: 8,
		value: 1,
		text: "Offer expired",
		color: "red",
	},
	{
		id: 2,
		title: "12 Months Subscription",
		totalPrice: 179,
		monthlyPrice: 15,
		value: 2,
		text: "Recommended",
		color: "#47BA68",
	},
	{
		id: 3,
		title: "6 Months Subscription",
		totalPrice: 149,
		monthlyPrice: 25,
		value: 3,
		text: "",
	},
	{
		id: 4,
		title: "6 Months Subscription",
		totalPrice: 99,
		monthlyPrice: 33,
		value: 4,
		text: "",
	},
];
